apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splice-api.fullname" . }}
  labels:
    {{- include "splice-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "splice-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "splice-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "splice-api.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.tmpDir.enabled }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- end }}
      {{- if .Values.tmpDir.enabled }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- end }}
