"""SECR workbook parser — turns a SECR .xlsx into structured engineering data.

This is the read side of the SECR database: it takes the bytes of a SECR
workbook (generated by :mod:`secrdb.core.secr.generate`, or an historical file an
engineer drops into the import panel) and returns a :class:`ParsedSecr` holding
the Summary metadata plus one :class:`ParsedChange` per *changed field*.

Where the data lives in a SECR workbook
---------------------------------------
``Summary``
    Header metadata (SECR #, version, MY, vehicle line, phase, harness family,
    DTCR #s, bulletin #s) and the affected-item roll-up blocks.
``Add_Remove_Report_Summary``
    Connector ADD / DELETE rows. Verified superset of the ADD/DELETE rows on
    the ``Connector`` sheet, so connector adds and deletes are read from here
    only — otherwise every add would be counted twice.
``Connector``
    Connector CHG / COMP CHG rows, with explicit ``(Old)`` columns.
``Circuit``
    Circuit ADD / DELETE / CHG / COMP CHG rows. Old values come from an
    explicit ``(Old)`` column where the sheet has one; otherwise from the cell
    comment the compare engine writes (``"Old DEF :X350A|1"``). Changed cells
    are additionally highlighted yellow.
``DEF_DEF_Summary``
    Harness-level part-number changes, one row per DEF symbol.

Nothing here invents values. A field whose old value cannot be recovered is
recorded with ``old_value=None`` and the record carries a warning, so the UI
can show the gap instead of a fabricated number.
"""

from __future__ import annotations

import hashlib
import io
import re
from dataclasses import dataclass, field as dataclass_field
from typing import Any, Dict, Iterable, List, Optional, Tuple

import openpyxl

from secrdb.core.common.errors import SpliceSchemaError

SUMMARY_SHEET = "Summary"
CONNECTOR_SHEET = "Connector"
CIRCUIT_SHEET = "Circuit"
ADD_REMOVE_SHEET = "Add_Remove_Report_Summary"
DEF_DEF_SUMMARY_SHEET = "DEF_DEF_Summary"

#: Action vocabulary as written by the compare engine into the SECR sheets.
FILE_ACTIONS = frozenset({"ADD", "DELETE", "CHG", "COMP CHG"})

#: Derived action: a DELETE and an ADD of the same CNUM in one SECR is how the
#: workbooks express "this connector's part number was replaced".
ACTION_PN_CHANGE = "PN CHANGE"

OBJECT_CONNECTOR = "connector"
OBJECT_CIRCUIT = "circuit"
OBJECT_PART_NUMBER = "part_number"
OBJECT_HARNESS = "harness"

#: Yellow fills used by the compare engine to mark a changed cell.
_YELLOW_FILLS = frozenset({"FFFFFF00", "FFFF00", "FFFFFF99"})

#: A DTCR is any standalone 5-digit number in an SE Comment.
#:
#: This deliberately does NOT require the word "DTCR". SEs write the number a
#: dozen ways — ``DTCR 49793``, ``DTCR-50326``, ``DTCR_50073``, ``DTCR D50351 &
#: D50298``, ``DTCR 50298 AND 50318``, and bare lists like ``Delete PHEV:
#: 49900/49951/49745`` — and a keyword-anchored pattern missed most of them.
#:
#: The width is exactly 5 because that is what separates a DTCR from the other
#: numbers in these comments: bulletins and part numbers are 6+ digits
#: (``320767``, ``318725``), cavities and gauges are 1-2. The lookarounds stop
#: a 5-digit run from being cut out of a longer number, so ``318725`` and
#: ``06092026`` contribute nothing.
_DTCR_RE = re.compile(r"(?<!\d)\d{5}(?!\d)")

# Summary cells, mirroring splice.secr.db.record_from_workbook.
_SUMMARY_CELLS = {
    "secr_number": "I2",
    "version": "I3",
    "workbook_name": "C8",
    "subject": "C7",
    "model_year": "C10",
    "program": "C11",
    "phase": "F10",
    "harness_family": "C12",
    "phase_implemented": "F11",
    "pull_ahead": "F12",
    "secr_author": "I10",
    "design_release_engineer": "I11",
    "change_requested_by": "I12",
    "dtcr_numbers": "C14",
    "bulletin_numbers": "G14",
    "ref_secr": "C15",
}

_AFFECTED_CELLS = [
    ("device", "ADD", "C20"),
    ("device", "CHG", "C21"),
    ("device", "DELETE", "C22"),
    ("circuit", "ADD", "C25"),
    ("circuit", "CHG", "C26"),
    ("circuit", "DELETE", "C27"),
    ("part_number", "ADD", "C30"),
    ("part_number", "CHG", "C31"),
    ("part_number", "DELETE", "C32"),
]

# Circuit columns that carry an explicit "old" twin. Everything else falls back
# to the cell comment.
_CIRCUIT_OLD_PAIRS = {
    "DEF CKT COLOR": "DEF CKT COLOR(Old)",
    "DEF GAUGE": "DEF GAUGE(Old)",
    "DEF_CKT_MATERIAL": "DEF_CKT_MATERIAL (Old)",
    "Sales_Code": "Sales_Code (Old)",
}

# Key/metadata columns that are never themselves a "changed field".
_CIRCUIT_IGNORED = frozenset(
    {"SE Comment", "SE Comments", "Action", "CKT NBR", "CKT Suffix"}
)


@dataclass(frozen=True)
class ParsedChange:
    """One changed field on one engineering object."""

    object_type: str
    object_id: str
    action: str
    source_sheet: str
    source_row: int
    field: Optional[str] = None
    old_value: Optional[str] = None
    new_value: Optional[str] = None
    dtcr_number: Optional[str] = None
    harness_pn: Optional[str] = None
    sales_code: Optional[str] = None
    se_comment: Optional[str] = None
    #: Where a circuit terminates, split out of ``CKT FROM/To (DNUM | CAV)``.
    #: A DNUM *is* an FCA-CNUM — the same connector namespace — so these make a
    #: circuit change findable by the connector it lands on. Circuit rows only.
    #:
    #: Both states are kept. A circuit *leaving* a pin is a change to that pin,
    #: so "has X501A cavity 7 changed?" has to see the row where the circuit
    #: moved away as well as the row where one arrived. The ``_old`` values
    #: equal their current twin unless that endpoint is what changed.
    from_dnum: Optional[str] = None
    from_cav: Optional[str] = None
    to_dnum: Optional[str] = None
    to_cav: Optional[str] = None
    from_dnum_old: Optional[str] = None
    from_cav_old: Optional[str] = None
    to_dnum_old: Optional[str] = None
    to_cav_old: Optional[str] = None


@dataclass
class ParsedSecr:
    """Everything the database stores about one SECR workbook."""

    secr_number: str
    version: str
    metadata: Dict[str, Any]
    affected_items: List[Dict[str, str]] = dataclass_field(default_factory=list)
    changes: List[ParsedChange] = dataclass_field(default_factory=list)
    dtcr_numbers: List[str] = dataclass_field(default_factory=list)
    bulletin_numbers: List[str] = dataclass_field(default_factory=list)
    warnings: List[str] = dataclass_field(default_factory=list)
    source_sha256: str = ""
    source_size: int = 0

    @property
    def change_count(self) -> int:
        return len(self.changes)


# ---------------------------------------------------------------------------
# Cell helpers
# ---------------------------------------------------------------------------

def _text(value: Any) -> str:
    if value is None:
        return ""
    if hasattr(value, "strftime"):
        return value.strftime("%Y-%m-%d")
    return str(value).strip()


def _header_text(value: Any) -> str:
    return re.sub(r"\s+", " ", _text(value)).strip()


def _optional(value: str) -> Optional[str]:
    return value or None


def split_list(text: Any) -> List[str]:
    """Split a comma/semicolon/newline separated cell into clean items."""
    raw = _text(text)
    if not raw:
        return []
    return [part.strip() for part in re.split(r"[,;\n]+", raw) if part.strip()]


def extract_dtcr_numbers(text: Any) -> List[str]:
    """Every DTCR named in a piece of free text, in the order written.

    A DTCR is any standalone 5-digit number — see :data:`_DTCR_RE` for why the
    word "DTCR" is not required and why 5 is the right width.
    """
    raw = _text(text)
    if not raw:
        return []
    found: List[str] = []
    for number in _DTCR_RE.findall(raw):
        if number not in found:
            found.append(number)
    return found


def _row_dtcrs(text: Any) -> Optional[str]:
    """The DTCRs for one change row, as stored in ``secr_change.dtcr_number``.

    A comment naming several DTCRs keeps all of them, comma-joined — the same
    shape :func:`secrdb.core.secr.generation.assign_dtcrs_to_cnums` already
    writes when the matching report ties one CNUM to several DTCRs. Keeping
    only the first silently dropped the rest, which made a DTCR that was always
    written second unqueryable.
    """
    numbers = extract_dtcr_numbers(text)
    return ", ".join(numbers) if numbers else None


def _is_marked_changed(cell) -> bool:
    """True when the compare engine marked this cell as the changed field."""
    try:
        rgb = cell.fill.fgColor.rgb
    except Exception:  # pragma: no cover - defensive, styles can be malformed
        rgb = None
    if rgb and str(rgb).upper() in _YELLOW_FILLS:
        return True
    return cell.comment is not None


def _old_value_from_comment(cell) -> Optional[str]:
    """Read the ``Old DEF :<value>`` comment the compare engine attaches."""
    if not cell.comment:
        return None
    text = (cell.comment.text or "").strip()
    match = re.search(r"old\s+def\s*:\s*(.*)", text, flags=re.IGNORECASE | re.DOTALL)
    value = match.group(1).strip() if match else text
    return value or None


#: Key column -> object kind. A header row is identified by carrying "Action"
#: plus exactly one of these keys.
_BLOCK_KEYS = {
    "FCA-CNUM": OBJECT_CONNECTOR,
    "CKT NBR": OBJECT_CIRCUIT,
    "Harness PN": OBJECT_HARNESS,
}


@dataclass(frozen=True)
class _Block:
    """One header row plus the data rows beneath it."""

    kind: str
    key_header: str
    header_row: int
    first_row: int
    last_row: int
    headers: Dict[str, int]


def _find_blocks(ws) -> List[_Block]:
    """Split a sheet into header-delimited blocks.

    Sheets are not laid out consistently: ``Add_Remove_Report_Summary`` holds
    *two* tables (a connector Add/Remove report followed by a circuit one),
    header rows sit on row 2 or 3 depending on the file, and a stray part
    number occasionally lands in an Action column. Finding the header rows
    first — rather than assuming row 3 and reading to the end of the sheet —
    keeps a circuit from being read as a connector.
    """
    max_row = ws.max_row or 0
    max_col = ws.max_column or 0
    candidates: List[Tuple[int, str, str, Dict[str, int]]] = []
    for row in range(1, max_row + 1):
        headers = {
            _header_text(ws.cell(row, col).value): col for col in range(1, max_col + 1)
        }
        headers.pop("", None)
        if "Action" not in headers:
            continue
        for key_header, kind in _BLOCK_KEYS.items():
            if key_header in headers:
                candidates.append((row, kind, key_header, headers))
                break

    blocks: List[_Block] = []
    for index, (header_row, kind, key_header, headers) in enumerate(candidates):
        next_header = (
            candidates[index + 1][0] if index + 1 < len(candidates) else max_row + 1
        )
        blocks.append(
            _Block(
                kind=kind,
                key_header=key_header,
                header_row=header_row,
                first_row=header_row + 1,
                last_row=next_header - 1,
                headers=headers,
            )
        )
    return blocks


def _blocks_of_kind(ws, kind: str) -> List[_Block]:
    return [block for block in _find_blocks(ws) if block.kind == kind]


def _cell(ws, row: int, headers: Dict[str, int], *names: str) -> str:
    for name in names:
        col = headers.get(name)
        if col:
            return _text(ws.cell(row, col).value)
    return ""


def _se_comment(ws, row: int, headers: Dict[str, int]) -> str:
    return _cell(ws, row, headers, "SE Comment", "SE Comments")


def _endpoint_cell(ws, row: int, headers: Dict[str, int], side: str) -> str:
    """The raw ``CKT FROM``/``CKT To`` cell, found by prefix.

    The two headers carry the same meaning but not the same spelling — the real
    workbooks write ``CKT FROM (DNUM | CAV)`` and ``CKT To (DNUM | CAV)``, one
    upper-case and one not — so they are matched case-insensitively by prefix
    rather than by an exact literal that a future template could break.
    """
    prefix = f"CKT {side}".upper()
    for name, col in headers.items():
        if name.upper().startswith(prefix):
            return _text(ws.cell(row, col).value)
    return ""


def endpoint_side(field_name: Any) -> Optional[str]:
    """``"CKT To (DNUM | CAV)"`` -> ``"TO"``; anything else -> ``None``."""
    header = _text(field_name).upper()
    if header.startswith("CKT FROM"):
        return "FROM"
    if header.startswith("CKT TO"):
        return "TO"
    return None


def _previous_endpoints(
    fields: List[Tuple[Optional[str], Optional[str], Optional[str]]],
) -> Dict[str, Tuple[Optional[str], Optional[str]]]:
    """Previous connector/cavity per side, for the sides that actually moved."""
    previous: Dict[str, Tuple[Optional[str], Optional[str]]] = {}
    for field_name, old_value, _new_value in fields:
        side = endpoint_side(field_name)
        if side and old_value:
            previous[side] = split_endpoint(old_value)
    return previous


def split_endpoint(value: Any) -> Tuple[Optional[str], Optional[str]]:
    """``"X501A|7"`` -> ``("X501A", "7")``. Returns ``(None, None)`` if unusable.

    The cavity is alphanumeric, not numeric: ``D3840A|C`` is as common as
    ``X501A|7`` (259 of the 5,636 endpoints in the validation set are lettered).
    """
    raw = _text(value)
    if "|" not in raw:
        return None, None
    dnum, _, cav = raw.partition("|")
    return (_optional(dnum.strip().upper()), _optional(cav.strip().upper()))


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def _parse_summary(ws) -> Tuple[Dict[str, Any], List[Dict[str, str]]]:
    metadata: Dict[str, Any] = {
        key: _text(ws[cell].value) for key, cell in _SUMMARY_CELLS.items()
    }
    metadata["original_issue_date"] = _text(ws["I4"].value)
    metadata["reissue_date"] = _text(ws["I5"].value)
    metadata["reason_for_change"] = _text(ws["B17"].value)

    affected: List[Dict[str, str]] = []
    for category, action, cell in _AFFECTED_CELLS:
        for item in split_list(ws[cell].value):
            affected.append({"category": category, "action": action, "item": item})
    return metadata, affected


# ---------------------------------------------------------------------------
# Connectors
# ---------------------------------------------------------------------------

def _connector_rows(ws, sheet_name: str) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for block in _blocks_of_kind(ws, OBJECT_CONNECTOR):
        headers = block.headers
        for row in range(block.first_row, block.last_row + 1):
            action = _cell(ws, row, headers, "Action").upper()
            cnum = _cell(ws, row, headers, "FCA-CNUM")
            if action not in FILE_ACTIONS or not cnum:
                continue
            rows.append(
                {
                    "sheet": sheet_name,
                    "row": row,
                    "action": action,
                    "cnum": cnum,
                    "pn_new": _cell(ws, row, headers, "DEF_Connector_PN"),
                    "pn_old": _cell(
                        ws,
                        row,
                        headers,
                        "DEF_Connector_PN(Old)",
                        "DEF_Connector_PN (Old)",
                    ),
                    "suffix_new": _cell(ws, row, headers, "Suffix(New)", "Suffix (New)"),
                    "suffix_old": _cell(ws, row, headers, "Suffix(Old)", "Suffix (Old)"),
                    "supplier": _cell(ws, row, headers, "DEF_Connector_Supplier"),
                    "se_comment": _se_comment(ws, row, headers),
                }
            )
    return rows


def _pair_pn_changes(
    rows: List[Dict[str, Any]]
) -> Tuple[List[Tuple[Dict[str, Any], Dict[str, Any]]], List[Dict[str, Any]]]:
    """Pair a DELETE with an ADD of the same CNUM into a part-number change."""
    by_cnum: Dict[str, Dict[str, List[Dict[str, Any]]]] = {}
    for row in rows:
        by_cnum.setdefault(row["cnum"], {}).setdefault(row["action"], []).append(row)

    pairs: List[Tuple[Dict[str, Any], Dict[str, Any]]] = []
    paired: set[int] = set()
    for actions in by_cnum.values():
        deletes = actions.get("DELETE", [])
        adds = actions.get("ADD", [])
        for deleted, added in zip(deletes, adds):
            pairs.append((deleted, added))
            paired.add(id(deleted))
            paired.add(id(added))
    unpaired = [row for row in rows if id(row) not in paired]
    return pairs, unpaired


def _dedupe_rows(
    primary: List[Dict[str, Any]], secondary: List[Dict[str, Any]], *keys: str
) -> List[Dict[str, Any]]:
    """``primary`` plus any ``secondary`` row it does not already cover.

    The same change is often written to two sheets (a connector DELETE appears
    on both ``Add_Remove_Report_Summary`` and ``Connector``). Taking the union
    and dropping exact key matches counts each change once without assuming one
    sheet is always a superset of the other — if a file ever disagrees, the
    extra rows are kept rather than silently dropped.
    """
    seen = {tuple(row[key] for key in keys) for row in primary}
    merged = list(primary)
    for row in secondary:
        signature = tuple(row[key] for key in keys)
        if signature not in seen:
            seen.add(signature)
            merged.append(row)
    return merged


def _parse_connectors(wb) -> Tuple[List[ParsedChange], List[str]]:
    """Connector adds/deletes/PN changes plus in-place connector changes.

    Adds and deletes are taken from ``Add_Remove_Report_Summary`` — verified
    across the historical corpus to be a superset of the ``Connector`` sheet's
    add/delete rows — and the ``Connector`` sheet contributes its CHG /
    COMP CHG rows plus anything the add/remove report happens to be missing.
    """
    changes: List[ParsedChange] = []
    warnings: List[str] = []

    add_remove_rows: List[Dict[str, Any]] = []
    if ADD_REMOVE_SHEET in wb.sheetnames:
        add_remove_rows = _connector_rows(wb[ADD_REMOVE_SHEET], ADD_REMOVE_SHEET)

    connector_rows: List[Dict[str, Any]] = []
    if CONNECTOR_SHEET in wb.sheetnames:
        connector_rows = _connector_rows(wb[CONNECTOR_SHEET], CONNECTOR_SHEET)

    connector_add_delete = [
        row for row in connector_rows if row["action"] in ("ADD", "DELETE")
    ]
    add_remove_rows = _dedupe_rows(
        add_remove_rows, connector_add_delete, "action", "cnum"
    )

    pairs, unpaired = _pair_pn_changes(add_remove_rows)

    for deleted, added in pairs:
        comment = added["se_comment"] or deleted["se_comment"]
        changes.append(
            ParsedChange(
                object_type=OBJECT_CONNECTOR,
                object_id=added["cnum"],
                action=ACTION_PN_CHANGE,
                field="DEF_Connector_PN",
                old_value=_optional(deleted["pn_old"] or deleted["pn_new"]),
                new_value=_optional(added["pn_new"]),
                dtcr_number=_row_dtcrs(comment),
                se_comment=_optional(comment),
                source_sheet=added["sheet"],
                source_row=added["row"],
            )
        )
        if added["suffix_new"] != deleted["suffix_old"]:
            changes.append(
                ParsedChange(
                    object_type=OBJECT_CONNECTOR,
                    object_id=added["cnum"],
                    action=ACTION_PN_CHANGE,
                    field="Suffix",
                    old_value=_optional(deleted["suffix_old"]),
                    new_value=_optional(added["suffix_new"]),
                    dtcr_number=_row_dtcrs(comment),
                    se_comment=_optional(comment),
                    source_sheet=added["sheet"],
                    source_row=added["row"],
                )
            )

    for row in unpaired:
        is_add = row["action"] == "ADD"
        changes.append(
            ParsedChange(
                object_type=OBJECT_CONNECTOR,
                object_id=row["cnum"],
                action=row["action"],
                field="DEF_Connector_PN",
                old_value=None if is_add else _optional(row["pn_old"] or row["pn_new"]),
                new_value=_optional(row["pn_new"]) if is_add else None,
                dtcr_number=_row_dtcrs(row["se_comment"]),
                se_comment=_optional(row["se_comment"]),
                source_sheet=row["sheet"],
                source_row=row["row"],
            )
        )

    for row in connector_rows:
        if row["action"] not in ("CHG", "COMP CHG"):
            continue
        emitted = False
        for label, old, new in (
            ("DEF_Connector_PN", row["pn_old"], row["pn_new"]),
            ("Suffix", row["suffix_old"], row["suffix_new"]),
        ):
            if old != new and (old or new):
                emitted = True
                changes.append(
                    ParsedChange(
                        object_type=OBJECT_CONNECTOR,
                        object_id=row["cnum"],
                        action=row["action"],
                        field=label,
                        old_value=_optional(old),
                        new_value=_optional(new),
                        dtcr_number=_row_dtcrs(row["se_comment"]),
                        se_comment=_optional(row["se_comment"]),
                        source_sheet=row["sheet"],
                        source_row=row["row"],
                    )
                )
        if not emitted:
            # A marked change we cannot attribute to a field — record it rather
            # than dropping it, with the SE comment as the only evidence.
            changes.append(
                ParsedChange(
                    object_type=OBJECT_CONNECTOR,
                    object_id=row["cnum"],
                    action=row["action"],
                    field=None,
                    old_value=None,
                    new_value=None,
                    dtcr_number=_row_dtcrs(row["se_comment"]),
                    se_comment=_optional(row["se_comment"]),
                    source_sheet=row["sheet"],
                    source_row=row["row"],
                )
            )
    return changes, warnings


# ---------------------------------------------------------------------------
# Circuits
# ---------------------------------------------------------------------------

def _circuit_changed_fields(
    ws, row: int, headers: Dict[str, int], header_row: int, action: str
) -> List[Tuple[str, Optional[str], Optional[str]]]:  # noqa: C901
    """Return ``(field, old_value, new_value)`` for each changed circuit field."""
    results: List[Tuple[str, Optional[str], Optional[str]]] = []
    for col in range(1, (ws.max_column or 1) + 1):
        header = _header_text(ws.cell(header_row, col).value)
        if not header or header in _CIRCUIT_IGNORED:
            continue
        if header.endswith("(Old)"):
            continue  # consumed as the old value of its twin
        # Trailing numeric columns are the per-harness variant matrix (X marks),
        # not engineering values.
        if re.fullmatch(r"\d+", header):
            continue

        cell = ws.cell(row, col)
        new_value = _text(cell.value)
        old_header = _CIRCUIT_OLD_PAIRS.get(header)
        old_value: Optional[str] = None
        changed = False

        if old_header and old_header in headers:
            old_value = _text(ws.cell(row, headers[old_header]).value)
            changed = old_value != new_value
            if action in ("ADD", "DELETE"):
                changed = bool(new_value or old_value)
        elif action in ("CHG", "COMP CHG"):
            if _is_marked_changed(cell):
                changed = True
                old_value = _old_value_from_comment(cell)
        else:  # ADD / DELETE: the whole row is the change
            changed = bool(new_value)

        if not changed:
            continue
        if action == "DELETE":
            results.append((header, _optional(new_value), None))
        elif action == "ADD":
            results.append((header, None, _optional(new_value)))
        else:
            results.append((header, _optional(old_value or ""), _optional(new_value)))
    return results


def _parse_circuit_blocks(ws, sheet_name: str) -> Tuple[List[ParsedChange], int]:
    changes: List[ParsedChange] = []
    unattributed = 0
    for block in _blocks_of_kind(ws, OBJECT_CIRCUIT):
        headers = block.headers
        for row in range(block.first_row, block.last_row + 1):
            action = _cell(ws, row, headers, "Action").upper()
            number = _cell(ws, row, headers, "CKT NBR")
            if action not in FILE_ACTIONS or not number:
                continue
            # The circuit identity engineers use (and that the Summary rollup
            # writes) is CKT NBR + CKT Suffix, e.g. A937 + F -> "A937F".
            circuit = number + _cell(ws, row, headers, "CKT Suffix")
            comment = _se_comment(ws, row, headers)
            dtcr = _row_dtcrs(comment)
            sales_code = _cell(ws, row, headers, "Sales_Code")
            # The endpoints belong to the circuit *row*, so every changed field
            # from that row carries them. That is what lets a DTCR be related
            # to a circuit together with the connectors and cavities it lands
            # on, without inventing a second row per endpoint.
            from_dnum, from_cav = split_endpoint(
                _endpoint_cell(ws, row, headers, "FROM")
            )
            to_dnum, to_cav = split_endpoint(
                _endpoint_cell(ws, row, headers, "TO")
            )
            fields = _circuit_changed_fields(
                ws, row, headers, block.header_row, action
            )
            # If an endpoint is what changed, its previous connector/cavity is
            # in that field's old value; otherwise the pin did not move and the
            # previous state is the current one.
            previous = _previous_endpoints(fields)
            from_dnum_old, from_cav_old = previous.get(
                "FROM", (from_dnum, from_cav)
            )
            to_dnum_old, to_cav_old = previous.get("TO", (to_dnum, to_cav))
            if not fields:
                unattributed += 1
                fields = [(None, None, None)]  # keep the row, flag the gap
            for field_name, old_value, new_value in fields:
                changes.append(
                    ParsedChange(
                        object_type=OBJECT_CIRCUIT,
                        object_id=circuit,
                        action=action,
                        field=field_name,
                        old_value=old_value,
                        new_value=new_value,
                        dtcr_number=dtcr,
                        sales_code=_optional(sales_code),
                        se_comment=_optional(comment),
                        source_sheet=sheet_name,
                        source_row=row,
                        from_dnum=from_dnum,
                        from_cav=from_cav,
                        to_dnum=to_dnum,
                        to_cav=to_cav,
                        from_dnum_old=from_dnum_old,
                        from_cav_old=from_cav_old,
                        to_dnum_old=to_dnum_old,
                        to_cav_old=to_cav_old,
                    )
                )
    return changes, unattributed


def _parse_circuits(wb) -> Tuple[List[ParsedChange], List[str]]:
    """Circuit changes, from the ``Circuit`` sheet and the add/remove report.

    The ``Circuit`` sheet is the richer source — it carries the CHG / COMP CHG
    rows and the paired ``(Old)`` columns — so it is read first and wins on
    conflict. The circuit block of ``Add_Remove_Report_Summary`` normally
    repeats its ADD/DELETE rows exactly; taking the union and deduping on
    circuit + action keeps that from double counting, while still capturing an
    add or delete that only one of the two sheets happens to record.
    """
    changes: List[ParsedChange] = []
    warnings: List[str] = []
    unattributed = 0

    if CIRCUIT_SHEET in wb.sheetnames:
        changes, unattributed = _parse_circuit_blocks(wb[CIRCUIT_SHEET], CIRCUIT_SHEET)

    if ADD_REMOVE_SHEET in wb.sheetnames:
        extra, extra_unattributed = _parse_circuit_blocks(
            wb[ADD_REMOVE_SHEET], ADD_REMOVE_SHEET
        )
        covered = {(c.object_id, c.action) for c in changes}
        new_rows = [c for c in extra if (c.object_id, c.action) not in covered]
        if new_rows:
            changes.extend(new_rows)
            unattributed += extra_unattributed

    if unattributed:
        warnings.append(
            f"{unattributed} circuit row(s) are marked changed but no changed "
            "field could be identified; recorded without old/new values."
        )
    return changes, warnings


# ---------------------------------------------------------------------------
# Harness part numbers (DEF_DEF_Summary)
# ---------------------------------------------------------------------------

def _parse_harness_pns(wb) -> Tuple[List[ParsedChange], List[str]]:
    changes: List[ParsedChange] = []
    warnings: List[str] = []
    if DEF_DEF_SUMMARY_SHEET not in wb.sheetnames:
        return changes, warnings

    ws = wb[DEF_DEF_SUMMARY_SHEET]
    blocks = _blocks_of_kind(ws, OBJECT_HARNESS)
    if not blocks:
        warnings.append(
            f"'{DEF_DEF_SUMMARY_SHEET}' sheet has no 'Harness PN' header; skipped."
        )
        return changes, warnings

    for block in blocks:
        headers = block.headers
        for row in range(block.first_row, block.last_row + 1):
            action = _cell(ws, row, headers, "Action").upper()
            if action not in FILE_ACTIONS:
                continue
            symbol = _cell(ws, row, headers, "DEF Symbol")
            pn_new = _cell(ws, row, headers, "Harness PN")
            pn_old = _cell(ws, row, headers, "Harness PN (Old)", "Harness PN(Old)")
            if not (symbol or pn_new or pn_old):
                continue
            comment = _se_comment(ws, row, headers)
            changes.append(
                ParsedChange(
                    object_type=OBJECT_HARNESS,
                    object_id=symbol or pn_new or pn_old,
                    action=action,
                    field="Harness PN",
                    old_value=_optional(pn_old),
                    new_value=_optional(pn_new),
                    dtcr_number=_row_dtcrs(comment),
                    harness_pn=_optional(pn_new or pn_old),
                    se_comment=_optional(comment),
                    source_sheet=DEF_DEF_SUMMARY_SHEET,
                    source_row=row,
                )
            )
    return changes, warnings


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

#: Summary affected-item category -> the change object_type that backs it. The
#: ``part_number`` block is excluded: it holds free text ("Symbols 447, 448")
#: that does not map one-to-one onto a change row.
_RECONCILE_CATEGORIES = {"device": OBJECT_CONNECTOR, "circuit": OBJECT_CIRCUIT}


def _reconcile_summary(
    affected_items: List[Dict[str, str]], changes: List[ParsedChange]
) -> List[str]:
    """Flag Summary roll-up entries that no change row accounts for.

    The Summary block and the change sheets are written by the same generator,
    so they normally agree. When they don't — a hand-edited Summary, or a
    workbook rebuilt against a different DEF — the roll-up is the only record
    that the item was touched. Both are kept; this warning makes the gap
    visible instead of letting the detail view look complete.
    """
    warnings: List[str] = []
    for category, object_type in _RECONCILE_CATEGORIES.items():
        listed = {
            item["item"] for item in affected_items if item["category"] == category
        }
        backed = {
            change.object_id for change in changes if change.object_type == object_type
        }
        missing = sorted(listed - backed)
        if missing:
            shown = ", ".join(missing[:10])
            more = f" (+{len(missing) - 10} more)" if len(missing) > 10 else ""
            warnings.append(
                f"Summary lists {len(missing)} {category} item(s) with no matching "
                f"row on the change sheets: {shown}{more}."
            )
    return warnings


def parse_secr_bytes(secr_bytes: bytes, *, filename: str = "") -> ParsedSecr:
    """Parse a SECR workbook into metadata + normalized change records.

    Raises :class:`SpliceSchemaError` when the file is not a SECR workbook (no
    ``Summary`` sheet) or carries no SECR number, which is the identity the
    database is keyed on.
    """
    if not secr_bytes:
        raise SpliceSchemaError("The SECR file is empty.")
    try:
        workbook = openpyxl.load_workbook(io.BytesIO(secr_bytes), data_only=True)
    except Exception as exc:  # noqa: BLE001 - any openpyxl failure is a bad file
        raise SpliceSchemaError(
            f"Could not read '{filename or 'the file'}' as an Excel workbook: {exc}"
        ) from exc

    try:
        if SUMMARY_SHEET not in workbook.sheetnames:
            raise SpliceSchemaError(
                f"'{filename or 'The file'}' has no '{SUMMARY_SHEET}' sheet, so it is "
                "not a SECR workbook."
            )
        metadata, affected_items = _parse_summary(workbook[SUMMARY_SHEET])
        secr_number = metadata.get("secr_number", "")
        if not secr_number:
            raise SpliceSchemaError(
                f"'{filename or 'The file'}' has no SECR # in Summary!I2."
            )

        changes: List[ParsedChange] = []
        warnings: List[str] = []
        for parser in (_parse_connectors, _parse_circuits, _parse_harness_pns):
            parsed_changes, parsed_warnings = parser(workbook)
            changes.extend(parsed_changes)
            warnings.extend(parsed_warnings)
    finally:
        workbook.close()

    dtcr_numbers = split_list(metadata.get("dtcr_numbers"))
    for change in changes:
        if change.dtcr_number and change.dtcr_number not in dtcr_numbers:
            dtcr_numbers.append(change.dtcr_number)

    if not changes:
        warnings.append(
            "No change rows were found on the Connector / Circuit / "
            "DEF_DEF_Summary sheets."
        )
    warnings.extend(_reconcile_summary(affected_items, changes))

    return ParsedSecr(
        secr_number=secr_number,
        version=metadata.get("version") or "A",
        metadata=metadata,
        affected_items=affected_items,
        changes=changes,
        dtcr_numbers=dtcr_numbers,
        bulletin_numbers=split_list(metadata.get("bulletin_numbers")),
        warnings=warnings,
        source_sha256=hashlib.sha256(secr_bytes).hexdigest(),
        source_size=len(secr_bytes),
    )


def summarize_changes(changes: Iterable[ParsedChange]) -> Dict[str, int]:
    """Count changes by action — used by the import report and the dashboard."""
    counts: Dict[str, int] = {}
    for change in changes:
        counts[change.action] = counts.get(change.action, 0) + 1
    return counts
