-- PostgreSQL / Supabase schema for production metrics persistence.
-- Uses UUID-like text ids generated by the application.

CREATE TABLE IF NOT EXISTS workflow_runs (
    id TEXT PRIMARY KEY,
    anonymous_user_id TEXT NULL,
    anonymous_session_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    workflow_version TEXT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL,
    status TEXT NOT NULL CHECK (status IN ('started', 'completed', 'failed', 'abandoned')),
    processing_seconds DOUBLE PRECISION NULL,
    input_file_count INTEGER NULL,
    output_file_count INTEGER NULL,
    rows_read INTEGER NULL,
    rows_processed INTEGER NULL,
    circuits_processed INTEGER NULL,
    harness_variants_processed INTEGER NULL,
    automatic_validation_errors INTEGER NULL,
    automatic_validation_warnings INTEGER NULL,
    automatic_validation_failures INTEGER NULL,
    output_generated BOOLEAN NULL,
    failure_category TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_workflow_runs_completed_at ON workflow_runs (completed_at);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_workflow_id ON workflow_runs (workflow_id);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_session_id ON workflow_runs (anonymous_session_id);

CREATE TABLE IF NOT EXISTS workflow_feedback (
    id TEXT PRIMARY KEY,
    workflow_run_id TEXT NOT NULL UNIQUE REFERENCES workflow_runs(id) ON DELETE CASCADE,
    workflow_id TEXT NOT NULL,
    anonymous_session_id TEXT NOT NULL,
    baseline_minutes INTEGER NULL,
    baseline_manual_touchpoints INTEGER NULL,
    remaining_manual_touchpoints INTEGER NULL,
    manual_touchpoints_eliminated INTEGER NULL,
    user_reported_errors_prevented INTEGER NULL,
    usefulness_rating INTEGER NULL CHECK (usefulness_rating BETWEEN 1 AND 5),
    non_confidential_feedback TEXT NULL,
    time_saved_minutes DOUBLE PRECISION NULL,
    time_savings_percentage DOUBLE PRECISION NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_workflow_feedback_created_at ON workflow_feedback (created_at);
CREATE INDEX IF NOT EXISTS idx_workflow_feedback_workflow_id ON workflow_feedback (workflow_id);
